/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package simulador;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Manuel
 */
public class Dialogo extends javax.swing.JDialog {

    private HashMap<String, Object> mapa;
    private ArrayList<Object> arrayGeneral;
    private ArrayList<Object> arrayConfigAntenas;
    private File archivoMapa;
    private File archivoModelo1;
    private File archivoModelo2;

    /**
     * Creates new form Dialogo
     */
    public Dialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        mapaFileChooser = new javax.swing.JFileChooser();
        antena1FileChooser = new javax.swing.JFileChooser();
        antena2FileChooser = new javax.swing.JFileChooser();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        pestañaConfiguracion = new javax.swing.JTabbedPane();
        ventanaParametros = new javax.swing.JPanel();
        labelFrec = new javax.swing.JLabel();
        labelRadio = new javax.swing.JLabel();
        frecuenciaSpinner = new javax.swing.JSpinner();
        labelCurv = new javax.swing.JLabel();
        labelPot = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelParam = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        labelParam2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        labelHeightMap = new javax.swing.JLabel();
        botonMapaFile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        resolucionComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelRuta = new javax.swing.JLabel();
        factorKSpinner = new javax.swing.JSpinner();
        potenciabox = new javax.swing.JComboBox<>();
        labelMedidas = new javax.swing.JLabel();
        coordX = new javax.swing.JSpinner();
        coordY = new javax.swing.JSpinner();
        coordZ = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        radioSpinner = new javax.swing.JSpinner();
        potenciaSpinner = new javax.swing.JSpinner();
        medidasXZ = new javax.swing.JSpinner();
        medidasY = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ventanaAntenas = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAntena1 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ganancia1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        rol1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        labelModelo1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        botonFile1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        sensibilidad1 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        perdidas1 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        alturaSpinner1 = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        panelAntena2 = new javax.swing.JPanel();
        nombreLabel2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ganancia2 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        rol2 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        labelModelo2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        botonFile2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        sensibilidad2 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        perdidas2 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        alturaSpinner2 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonOk = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        mapaFileChooser.setFileFilter(new FileNameExtensionFilter(
            "imagenes PNG y JPG ","jpg", "png"));

    antena1FileChooser.setFileFilter(new FileNameExtensionFilter(
        "archivos OBJ", "obj"));
antena1FileChooser.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        antena1FileChooserActionPerformed(evt);
    }
    });

    antena2FileChooser.setFileFilter(new FileNameExtensionFilter(
        "archivos OBJ", "obj"));
antena2FileChooser.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        antena2FileChooserActionPerformed(evt);
    }
    });

    addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent evt) {
            closeDialog(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel1.setText("Bienvendo a RadioSimu v1.00 ");
    panelTitulo.add(jLabel1);

    add(panelTitulo, java.awt.BorderLayout.NORTH);

    panelCentral.setAlignmentX(0.9F);

    pestañaConfiguracion.setToolTipText("pestaña de configuraciones");
    pestañaConfiguracion.setName("pestañaConfiguracion"); // NOI18N
    pestañaConfiguracion.setPreferredSize(new java.awt.Dimension(600, 400));

    ventanaParametros.setLayout(null);

    labelFrec.setText("Frecuencia de Transmision (Mhz.)");
    ventanaParametros.add(labelFrec);
    labelFrec.setBounds(30, 50, 184, 20);

    labelRadio.setText("Radio de la Tierra ");
    ventanaParametros.add(labelRadio);
    labelRadio.setBounds(250, 50, 180, 15);

    frecuenciaSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(30.0f), Float.valueOf(30.0f), Float.valueOf(300.0f), Float.valueOf(1.0f)));
    frecuenciaSpinner.setToolTipText("Escoja un valor entre los 30Mhz. y los 30Ghz."); // NOI18N
    frecuenciaSpinner.setInheritsPopupMenu(true);
    ventanaParametros.add(frecuenciaSpinner);
    frecuenciaSpinner.setBounds(70, 80, 120, 26);

    labelCurv.setText("Factor de Curvatura de la Tierra ");
    ventanaParametros.add(labelCurv);
    labelCurv.setBounds(40, 120, 180, 20);

    labelPot.setText("Potencia de la señal ");
    ventanaParametros.add(labelPot);
    labelPot.setBounds(280, 120, 150, 20);
    ventanaParametros.add(jSeparator1);
    jSeparator1.setBounds(250, 20, 200, 10);

    labelParam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    labelParam.setText("Parametros del enlace");
    ventanaParametros.add(labelParam);
    labelParam.setBounds(110, 10, 190, 20);
    ventanaParametros.add(jSeparator2);
    jSeparator2.setBounds(40, 20, 50, 0);
    ventanaParametros.add(jSeparator3);
    jSeparator3.setBounds(10, 20, 90, 10);
    ventanaParametros.add(jSeparator4);
    jSeparator4.setBounds(250, 200, 200, 10);

    labelParam2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    labelParam2.setText("Parametros del mapa");
    ventanaParametros.add(labelParam2);
    labelParam2.setBounds(110, 190, 190, 20);
    ventanaParametros.add(jSeparator5);
    jSeparator5.setBounds(10, 200, 90, 10);

    labelHeightMap.setText("Ruta del HeightMap");
    ventanaParametros.add(labelHeightMap);
    labelHeightMap.setBounds(340, 220, 120, 15);

    botonMapaFile.setText("...");
    botonMapaFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonMapaFile.setComponentPopupMenu(null);
    botonMapaFile.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonMapaFileActionPerformed(evt);
        }
    });
    ventanaParametros.add(botonMapaFile);
    botonMapaFile.setBounds(530, 240, 30, 19);

    jLabel9.setText("Resolución");
    ventanaParametros.add(jLabel9);
    jLabel9.setBounds(410, 280, 80, 15);

    resolucionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "800x600", "1024x720", "1360x768" }));
    resolucionComboBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            resolucionComboBoxActionPerformed(evt);
        }
    });
    ventanaParametros.add(resolucionComboBox);
    resolucionComboBox.setBounds(380, 300, 130, 27);

    jLabel10.setText("Coordenadas centrales del mapa (Opcional)");
    ventanaParametros.add(jLabel10);
    jLabel10.setBounds(30, 300, 260, 15);

    jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel11.setText("X");
    ventanaParametros.add(jLabel11);
    jLabel11.setBounds(110, 330, 20, 20);

    jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel12.setText("X");
    ventanaParametros.add(jLabel12);
    jLabel12.setBounds(220, 330, 8, 20);

    labelRuta.setBackground(new java.awt.Color(228, 231, 255));
    labelRuta.setToolTipText(labelRuta.getText());
    labelRuta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    labelRuta.setName("labelRuta"); // NOI18N
    ventanaParametros.add(labelRuta);
    labelRuta.setBounds(310, 240, 210, 20);

    factorKSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.333f), Float.valueOf(1.0f), Float.valueOf(4.0f), Float.valueOf(0.001f)));
    ventanaParametros.add(factorKSpinner);
    factorKSpinner.setBounds(70, 150, 120, 26);

    potenciabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dBm", "mW", "W" }));
    potenciabox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            potenciaboxActionPerformed(evt);
        }
    });
    ventanaParametros.add(potenciabox);
    potenciabox.setBounds(410, 150, 70, 27);

    labelMedidas.setText("Medidas  del Terreno");
    ventanaParametros.add(labelMedidas);
    labelMedidas.setBounds(50, 220, 190, 20);

    coordX.setModel(new javax.swing.SpinnerNumberModel());
    ventanaParametros.add(coordX);
    coordX.setBounds(20, 330, 80, 26);

    coordY.setModel(new javax.swing.SpinnerNumberModel());
    coordY.setToolTipText("");
    ventanaParametros.add(coordY);
    coordY.setBounds(130, 330, 80, 26);

    coordZ.setModel(new javax.swing.SpinnerNumberModel());
    ventanaParametros.add(coordZ);
    coordZ.setBounds(240, 330, 80, 26);

    jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel21.setText("Kmt.");
    ventanaParametros.add(jLabel21);
    jLabel21.setBounds(410, 80, 60, 20);

    radioSpinner.setModel(new javax.swing.SpinnerNumberModel(6000, 1000, 13000, 1));
    radioSpinner.setToolTipText("El valor real del radio terrestre es aproximadamente 6500 kmt. pueden usarse otros valores para experimentar.");
    ventanaParametros.add(radioSpinner);
    radioSpinner.setBounds(250, 80, 140, 26);

    potenciaSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
    ventanaParametros.add(potenciaSpinner);
    potenciaSpinner.setBounds(250, 150, 140, 26);

    medidasXZ.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), Float.valueOf(20.0f), Float.valueOf(1.0f)));
    medidasXZ.setToolTipText("Se sobreentiende que el ancho y el largo del heightmap tienen las mismas dimensiones");
    ventanaParametros.add(medidasXZ);
    medidasXZ.setBounds(30, 270, 80, 26);

    medidasY.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.255f), Float.valueOf(0.255f), Float.valueOf(3.0f), Float.valueOf(0.001f)));
    ventanaParametros.add(medidasY);
    medidasY.setBounds(180, 270, 80, 26);

    jLabel5.setText("Altura (Kmt.)");
    ventanaParametros.add(jLabel5);
    jLabel5.setBounds(190, 250, 80, 15);

    jLabel6.setText("Ancho/Largo (Kmt.)");
    ventanaParametros.add(jLabel6);
    jLabel6.setBounds(30, 250, 130, 20);

    pestañaConfiguracion.addTab("Enlace y Mapa", ventanaParametros);

    ventanaAntenas.setLayout(null);

    jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

    panelAntena1.setLayout(null);

    nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    nombreLabel.setText("Nombre :");
    panelAntena1.add(nombreLabel);
    nombreLabel.setBounds(60, 20, 70, 20);

    nombre1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nombre1ActionPerformed(evt);
        }
    });
    panelAntena1.add(nombre1);
    nombre1.setBounds(160, 20, 280, 25);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel2.setText("Ganacia : ");
    panelAntena1.add(jLabel2);
    jLabel2.setBounds(60, 60, 60, 20);

    ganancia1.setModel(new javax.swing.SpinnerNumberModel());
    panelAntena1.add(ganancia1);
    ganancia1.setBounds(170, 60, 130, 26);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel3.setText("Rol :");
    panelAntena1.add(jLabel3);
    jLabel3.setBounds(80, 100, 30, 30);

    rol1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transmisor", "Receptor" }));
    rol1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rol1ActionPerformed(evt);
        }
    });
    panelAntena1.add(rol1);
    rol1.setBounds(170, 100, 130, 27);

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel4.setText("Ruta del Modelo : ");
    jLabel4.setToolTipText("Si no se selecciona ningun modelo 3D,  se utilizará el que viene por defecto.");
    panelAntena1.add(jLabel4);
    jLabel4.setBounds(60, 260, 190, 40);

    labelModelo1.setBackground(new java.awt.Color(255, 255, 255));
    labelModelo1.setToolTipText("");
    labelModelo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    panelAntena1.add(labelModelo1);
    labelModelo1.setBounds(60, 300, 270, 20);

    jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel16.setText("dBi");
    panelAntena1.add(jLabel16);
    jLabel16.setBounds(320, 60, 60, 20);

    botonFile1.setText("...");
    botonFile1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonFile1.setComponentPopupMenu(null);
    botonFile1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonFile1ActionPerformed(evt);
        }
    });
    panelAntena1.add(botonFile1);
    botonFile1.setBounds(340, 300, 30, 20);

    jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel17.setText("Sensibilidad : ");
    panelAntena1.add(jLabel17);
    jLabel17.setBounds(60, 140, 90, 20);

    sensibilidad1.setModel(new javax.swing.SpinnerNumberModel());
    panelAntena1.add(sensibilidad1);
    sensibilidad1.setBounds(170, 140, 130, 26);

    jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel18.setText("Perdidas de Linea : ");
    panelAntena1.add(jLabel18);
    jLabel18.setBounds(40, 180, 130, 20);
    panelAntena1.add(perdidas1);
    perdidas1.setBounds(170, 180, 130, 26);

    jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel19.setText("dBm");
    panelAntena1.add(jLabel19);
    jLabel19.setBounds(320, 140, 50, 20);

    jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel20.setText("dB");
    panelAntena1.add(jLabel20);
    jLabel20.setBounds(320, 180, 60, 20);

    jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel33.setText("Altura : ");
    panelAntena1.add(jLabel33);
    jLabel33.setBounds(80, 220, 80, 20);

    alturaSpinner1.setModel(new javax.swing.SpinnerNumberModel(20.0f, 20.0f, null, 1.0f));
    panelAntena1.add(alturaSpinner1);
    alturaSpinner1.setBounds(170, 220, 130, 26);

    jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel34.setText("metros");
    panelAntena1.add(jLabel34);
    jLabel34.setBounds(320, 220, 60, 20);

    jTabbedPane1.addTab("Antena 1", panelAntena1);

    panelAntena2.setLayout(null);

    nombreLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    nombreLabel2.setText("Nombre :");
    panelAntena2.add(nombreLabel2);
    nombreLabel2.setBounds(60, 20, 70, 20);

    nombre2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nombre2ActionPerformed(evt);
        }
    });
    panelAntena2.add(nombre2);
    nombre2.setBounds(160, 20, 280, 25);

    jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel22.setText("Ganacia : ");
    panelAntena2.add(jLabel22);
    jLabel22.setBounds(60, 60, 60, 20);

    ganancia2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
    panelAntena2.add(ganancia2);
    ganancia2.setBounds(170, 60, 130, 26);

    jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel23.setText("Rol :");
    panelAntena2.add(jLabel23);
    jLabel23.setBounds(80, 100, 30, 30);

    rol2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transmisor", "Receptor" }));
    rol2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rol2ActionPerformed(evt);
        }
    });
    panelAntena2.add(rol2);
    rol2.setBounds(170, 100, 130, 27);

    jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel24.setText("Ruta del Modelo : ");
    jLabel24.setToolTipText("Si no se selecciona ningun modelo 3D,  se utilizará el que viene por defecto.");
    panelAntena2.add(jLabel24);
    jLabel24.setBounds(60, 260, 160, 40);

    labelModelo2.setBackground(new java.awt.Color(255, 255, 255));
    labelModelo2.setToolTipText("");
    labelModelo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    panelAntena2.add(labelModelo2);
    labelModelo2.setBounds(60, 300, 270, 20);

    jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel26.setText("dBi");
    panelAntena2.add(jLabel26);
    jLabel26.setBounds(320, 60, 60, 20);

    botonFile2.setText("...");
    botonFile2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonFile2.setComponentPopupMenu(null);
    botonFile2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonFile2ActionPerformed(evt);
        }
    });
    panelAntena2.add(botonFile2);
    botonFile2.setBounds(340, 300, 30, 20);

    jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel27.setText("Sensibilidad : ");
    panelAntena2.add(jLabel27);
    jLabel27.setBounds(60, 140, 90, 20);

    sensibilidad2.setModel(new javax.swing.SpinnerNumberModel());
    panelAntena2.add(sensibilidad2);
    sensibilidad2.setBounds(170, 140, 130, 26);

    jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel28.setText("Perdidas de Linea : ");
    panelAntena2.add(jLabel28);
    jLabel28.setBounds(40, 180, 130, 20);
    panelAntena2.add(perdidas2);
    perdidas2.setBounds(170, 180, 130, 26);

    jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel29.setText("dBm");
    panelAntena2.add(jLabel29);
    jLabel29.setBounds(320, 140, 50, 20);

    jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel30.setText("dB");
    panelAntena2.add(jLabel30);
    jLabel30.setBounds(320, 180, 60, 20);

    jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel31.setText("Altura : ");
    panelAntena2.add(jLabel31);
    jLabel31.setBounds(80, 220, 80, 20);

    alturaSpinner2.setModel(new javax.swing.SpinnerNumberModel(20.0f, 20.0f, null, 1.0f));
    panelAntena2.add(alturaSpinner2);
    alturaSpinner2.setBounds(170, 220, 130, 26);

    jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel32.setText("metros");
    panelAntena2.add(jLabel32);
    jLabel32.setBounds(320, 220, 60, 20);

    jTabbedPane1.addTab("Antena 2", panelAntena2);

    ventanaAntenas.add(jTabbedPane1);
    jTabbedPane1.setBounds(0, 0, 580, 360);
    jTabbedPane1.getAccessibleContext().setAccessibleName("Antena 2");

    pestañaConfiguracion.addTab("Antenas", ventanaAntenas);

    panelCentral.add(pestañaConfiguracion);

    add(panelCentral, java.awt.BorderLayout.WEST);

    botonOk.setText("OK");
    grupoBotones.add(botonOk);
    botonOk.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonOkActionPerformed(evt);
        }
    });

    botonCancelar.setText("CANCELAR");
    grupoBotones.add(botonCancelar);
    botonCancelar.setName("botonCancelar"); // NOI18N
    botonCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonCancelarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
    panelBotones.setLayout(panelBotonesLayout);
    panelBotonesLayout.setHorizontalGroup(
        panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBotonesLayout.createSequentialGroup()
            .addGap(188, 188, 188)
            .addComponent(botonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(48, 48, 48)
            .addComponent(botonCancelar)
            .addContainerGap())
    );
    panelBotonesLayout.setVerticalGroup(
        panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(botonCancelar)
            .addComponent(botonOk))
    );

    add(panelBotones, java.awt.BorderLayout.SOUTH);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void botonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkActionPerformed
        // TODO add your handling code here:
        if (evt.getSource().equals(botonOk)) {
            arrayGeneral = new ArrayList<>();
            arrayConfigAntenas = new ArrayList<>();
            mapa = new HashMap<String, Object>();
            mapa.put("frecuencia", frecuenciaSpinner.getValue());
            mapa.put("potencia", this.potenciaSpinner.getValue());
            mapa.put("radioTerrestre", radioSpinner.getValue());
            mapa.put("factorCurvatura", factorKSpinner.getValue());
            mapa.put("formatoPotencia", potenciabox.getSelectedIndex());
            mapa.put("coordX", coordX.getValue());
            mapa.put("coordY", coordY.getValue());
            mapa.put("coordZ", coordZ.getValue());
            mapa.put("medidasX", medidasXZ.getValue());
            mapa.put("medidasZ", medidasXZ.getValue());
            mapa.put("medidasY", medidasY.getValue());
            mapa.put("resolucion", resolucionComboBox.getSelectedIndex());
            mapa.put("heightmap", archivoMapa);

            HashMap<String, Object> config1 = new HashMap<String, Object>();
            config1.put("nombre", nombre1.getText());
            config1.put("ganancia", ganancia1.getValue());
            config1.put("rol", rol1.getSelectedIndex());
            config1.put("sensibilidad", sensibilidad1.getValue());
            config1.put("perdidas", perdidas1.getValue());
            config1.put("modelo", this.archivoModelo1);
            config1.put("altura", alturaSpinner1.getValue());

            HashMap<String, Object> config2 = new HashMap<String, Object>();
            config2.put("nombre", nombre2.getText());
            config2.put("ganancia", ganancia2.getValue());
            config2.put("rol", rol2.getSelectedIndex());
            config2.put("sensibilidad", sensibilidad2.getValue());
            config2.put("perdidas", perdidas2.getValue());
            config2.put("modelo", this.archivoModelo2);
            config2.put("altura", alturaSpinner2.getValue());

            arrayConfigAntenas.add(0, config1);
            arrayConfigAntenas.add(1, config2);
            arrayGeneral.add(0, mapa);
            arrayGeneral.add(1,arrayConfigAntenas);
            getValores();
            this.dispose();
            
        }

    }//GEN-LAST:event_botonOkActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void rol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rol1ActionPerformed

    private void botonFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFile1ActionPerformed
        // TODO add your handling code here:
        int opcion = antena1FileChooser.showOpenDialog(ventanaAntenas);
        if(opcion == JFileChooser.APPROVE_OPTION){
            this.archivoModelo1 = this.antena1FileChooser.getSelectedFile();
            labelModelo1.setText(archivoModelo1.getPath());
                    }
    }//GEN-LAST:event_botonFile1ActionPerformed

    private void nombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre2ActionPerformed

    private void rol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rol2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rol2ActionPerformed

    private void botonFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFile2ActionPerformed
        // TODO add your handling code here:
           int opcion = antena2FileChooser.showOpenDialog(ventanaAntenas);
        if(opcion == JFileChooser.APPROVE_OPTION){
            this.archivoModelo2 = this.antena2FileChooser.getSelectedFile();
            labelModelo2.setText(archivoModelo2.getPath());
                    }
        
    }//GEN-LAST:event_botonFile2ActionPerformed

    private void antena1FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antena1FileChooserActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_antena1FileChooserActionPerformed

    private void antena2FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antena2FileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antena2FileChooserActionPerformed

    private void potenciaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potenciaboxActionPerformed

    private void resolucionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolucionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resolucionComboBoxActionPerformed

    private void botonMapaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMapaFileActionPerformed
        int entero = mapaFileChooser.showOpenDialog(ventanaParametros);
        if (entero == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                + mapaFileChooser.getSelectedFile().getName());
            this.archivoMapa = mapaFileChooser.getSelectedFile();
            this.labelRuta.setText(mapaFileChooser.getSelectedFile().getPath());
            labelRuta.setToolTipText(mapaFileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_botonMapaFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo dialog = new Dialogo(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ArrayList<Object> getValores() {

        setVisible(true);

        return arrayGeneral;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner alturaSpinner1;
    private javax.swing.JSpinner alturaSpinner2;
    private javax.swing.JFileChooser antena1FileChooser;
    private javax.swing.JFileChooser antena2FileChooser;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonFile1;
    private javax.swing.JButton botonFile2;
    private javax.swing.JButton botonMapaFile;
    private javax.swing.JButton botonOk;
    private javax.swing.JSpinner coordX;
    private javax.swing.JSpinner coordY;
    private javax.swing.JSpinner coordZ;
    private javax.swing.JSpinner factorKSpinner;
    private javax.swing.JSpinner frecuenciaSpinner;
    private javax.swing.JSpinner ganancia1;
    private javax.swing.JSpinner ganancia2;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCurv;
    private javax.swing.JLabel labelFrec;
    private javax.swing.JLabel labelHeightMap;
    private javax.swing.JLabel labelMedidas;
    private javax.swing.JLabel labelModelo1;
    private javax.swing.JLabel labelModelo2;
    private javax.swing.JLabel labelParam;
    private javax.swing.JLabel labelParam2;
    private javax.swing.JLabel labelPot;
    private javax.swing.JLabel labelRadio;
    private javax.swing.JLabel labelRuta;
    private javax.swing.JFileChooser mapaFileChooser;
    private javax.swing.JSpinner medidasXZ;
    private javax.swing.JSpinner medidasY;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel2;
    private javax.swing.JPanel panelAntena1;
    private javax.swing.JPanel panelAntena2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner perdidas1;
    private javax.swing.JSpinner perdidas2;
    private javax.swing.JTabbedPane pestañaConfiguracion;
    private javax.swing.JSpinner potenciaSpinner;
    private javax.swing.JComboBox<String> potenciabox;
    private javax.swing.JSpinner radioSpinner;
    private javax.swing.JComboBox<String> resolucionComboBox;
    private javax.swing.JComboBox<String> rol1;
    private javax.swing.JComboBox<String> rol2;
    private javax.swing.JSpinner sensibilidad1;
    private javax.swing.JSpinner sensibilidad2;
    private javax.swing.JPanel ventanaAntenas;
    private javax.swing.JPanel ventanaParametros;
    // End of variables declaration//GEN-END:variables
}
